// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpGbiou7Wah63nZxMLDyN5lPz4cPO1pFg',
    appId: '1:942412802051:web:8e9ee4aea800378caf8636',
    messagingSenderId: '942412802051',
    projectId: 'elearning-testdb',
    authDomain: 'elearning-testdb.firebaseapp.com',
    storageBucket: 'elearning-testdb.appspot.com',
    measurementId: 'G-WF37RYX8BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_KA1YRw7ipPB30DSwwybKrYGTX9Mtvtk',
    appId: '1:942412802051:android:6b077e0b38458d1baf8636',
    messagingSenderId: '942412802051',
    projectId: 'elearning-testdb',
    storageBucket: 'elearning-testdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi0LJTuJf6RvgFHcc57PtIlLIbfJaag18',
    appId: '1:942412802051:ios:13dfa01584a4fa50af8636',
    messagingSenderId: '942412802051',
    projectId: 'elearning-testdb',
    storageBucket: 'elearning-testdb.appspot.com',
    iosBundleId: 'com.example.elearny',
  );
}
